version: '3'  # 定义 docker-compose 文件版本，3.x 版本的 Compose 文件格式(和 Docker Compose版本不是一回事)

services:
  docker_test:
    # 使用从阿里云镜像仓库拉取的 docker_test 镜像
    image: registry.cn-beijing.aliyuncs.com/peilongchencc_docker_hub/docker_test:latest
    
    # 将宿主机的 8848 端口映射到容器的 8848 端口
    ports:
      - "8848:8848"
    
    # 无论何时停止，都自动重启容器(生产环境很有用)
    restart: always
    container_name: my_docker_test  # 指定容器名称(对应服务启动后的 "NAMES")
